### ISSUE TITLE
error when convert pytorch model to Torch Script

### ISSUE THREAD

**Issue by zhiweizhong** [mit-han-lab/temporal-shift-module#59]
I'm trying to convert .pth file to trace file, and relate code is:

```
    import torch
    from ops.models import TSN

    this_weights = "./model/TSM_RGB_resnet50_shift8_blockres_avg_segment8_e25.pth.tar"
    net = TSN(25, 8, 'RGB',
              base_model='resnet50',
              consensus_type='avg',
              img_feature_dim=256,
              pretrain='imagenet',
              is_shift=True, shift_div=8, shift_place='blockres',
              non_local=False,
              )
    checkpoint = torch.load(this_weights)
    checkpoint = checkpoint['state_dict']

    base_dict = {'.'.join(k.split('.')[1:]): v for k, v in list(checkpoint.items())}
    replace_dict = {'base_model.classifier.weight': 'new_fc.weight',
                    'base_model.classifier.bias': 'new_fc.bias',
                    }
    for k, v in replace_dict.items():
        if k in base_dict:
            base_dict[v] = base_dict.pop(k)

    net.load_state_dict(base_dict)
     
    net.eval()

    data = torch.ones(1,3,8,224,224)
    traced_script_module = torch.jit.trace(net,data)
    traced_script_module.save("torch_script_eval.pt")
    
```
 
but it give me waring and error：

```
/home/zhongzhiwei/video_analyze/temporal-shift-module/ops/temporal_shift.py:43: TracerWarning: Converting a tensor to a Python index might cause the trace to be incorrect. We can't record the data flow of Pyth
on values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  out[:, :-1, :fold] = x[:, 1:, :fold]  # shift left
/home/zhongzhiwei/video_analyze/temporal-shift-module/ops/temporal_shift.py:44: TracerWarning: Converting a tensor to a Python index might cause the trace to be incorrect. We can't record the data flow of Pyth
on values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  out[:, 1:, fold: 2 * fold] = x[:, :-1, fold: 2 * fold]  # shift right
/home/zhongzhiwei/video_analyze/temporal-shift-module/ops/temporal_shift.py:45: TracerWarning: Converting a tensor to a Python index might cause the trace to be incorrect. We can't record the data flow of Pyth
on values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  out[:, :, 2 * fold:] = x[:, :, 2 * fold:]  # not shift
Traceback (most recent call last):
  File "model_convert.py", line 97, in <module>
    traced_script_module = torch.jit.trace(net,data)
  File "/home/zhongzhiwei/anaconda3/envs/tsm/lib/python3.6/site-packages/torch/jit/__init__.py", line 636, in trace
    var_lookup_fn, _force_outplace)
  File "/home/zhongzhiwei/anaconda3/envs/tsm/lib/python3.6/site-packages/torch/nn/modules/module.py", line 487, in __call__
    result = self._slow_forward(*input, **kwargs)
  File "/home/zhongzhiwei/anaconda3/envs/tsm/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/zhongzhiwei/video_analyze/temporal-shift-module/ops/models.py", line 286, in forward
    output = self.consensus(base_out)
  File "/home/zhongzhiwei/anaconda3/envs/tsm/lib/python3.6/site-packages/torch/nn/modules/module.py", line 487, in __call__
    result = self._slow_forward(*input, **kwargs)
  File "/home/zhongzhiwei/anaconda3/envs/tsm/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/zhongzhiwei/video_analyze/temporal-shift-module/ops/basic_ops.py", line 46, in forward
    return SegmentConsensus(self.consensus_type, self.dim)(input)
RuntimeError: Attempted to trace SegmentConsensus, but tracing of legacy functions is not supported
```

**Comment by tonylins** [comment]
Hi, are you using the most up-to-date code? I have modified function SegmentConsensus to be using nn.Module. It should be more compatible.

**Comment by zhiweizhong** [comment]
Ok, I will try the new code. thanks!
