### ISSUE TITLE
Finetuning on UCF101: Assertion cur_target >= 0 && cur_target < n_classes

### ISSUE THREAD

**Issue by Fritskee** [mit-han-lab/temporal-shift-module#95]
Hello, 

When I try to run the _finetune_tsm_ucf101_rgb_8f.sh_ script, I get the following error:

> Traceback (most recent call last):
  File "main.py", line 380, in <module>
    main()
  File "main.py", line 196, in main
    train(train_loader, model, criterion, optimizer, epoch, log_training, tf_writer)
  File "main.py", line 247, in train
    loss = criterion(output, target_var)
  File "/anaconda3/envs/ml/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/anaconda3/envs/ml/lib/python3.6/site-packages/torch/nn/modules/loss.py", line 942, in forward
    ignore_index=self.ignore_index, reduction=self.reduction)
  File "/anaconda3/envs/ml/lib/python3.6/site-packages/torch/nn/functional.py", line 2056, in cross_entropy
    return nll_loss(log_softmax(input, 1), target, weight, None, ignore_index, None, reduction)
  File "/anaconda3/envs/ml/lib/python3.6/site-packages/torch/nn/functional.py", line 1871, in nll_loss
    ret = torch._C._nn.nll_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index)
RuntimeError: Assertion `cur_target >= 0 && cur_target < n_classes' failed.  at ../aten/src/THNN/generic/ClassNLLCriterion.c:92

I have encountered this error before in other projects, and back then it meant that I had a mismatch between the amount of classes in my final layer, and the amount of classes that are present in the dataset.

Since I do not have access to the actual model here (at least I could only find that it loads in the PyTorch ResNet), I cannot make these changes.

Anybody had a similar error? and how did you fix it?

**Comment by cherylngsy** [comment]
did you resolve it?
